[mypy]
ignore_missing_imports = True
no_strict_optional = True
exclude = (?x)(^venv/ | ^tests/)

[mypy-transformers.*]
follow_imports = skip
ignore_errors = True

[mypy-sentence_transformers.*]
follow_imports = skip
ignore_errors = True